// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtlOg8InrWTMs96Ch7snJ3SgcbuzfsZQ',
    appId: '1:246973295693:web:2f84ac5e1e3af733dc0004',
    messagingSenderId: '246973295693',
    projectId: 'my-protfolio-dashboard',
    authDomain: 'my-protfolio-dashboard.firebaseapp.com',
    storageBucket: 'my-protfolio-dashboard.firebasestorage.app',
    measurementId: 'G-WGXEP2RZJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvbAxYEpxIkVYKMxVWLXcnZU2KpC3W2l0',
    appId: '1:246973295693:android:0b88b1d8be01e1fedc0004',
    messagingSenderId: '246973295693',
    projectId: 'my-protfolio-dashboard',
    storageBucket: 'my-protfolio-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqVpEqWiXHjWviMw0o10NeMXp_Kajzeo',
    appId: '1:246973295693:ios:50a742ab32b91729dc0004',
    messagingSenderId: '246973295693',
    projectId: 'my-protfolio-dashboard',
    storageBucket: 'my-protfolio-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.website',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLqVpEqWiXHjWviMw0o10NeMXp_Kajzeo',
    appId: '1:246973295693:ios:50a742ab32b91729dc0004',
    messagingSenderId: '246973295693',
    projectId: 'my-protfolio-dashboard',
    storageBucket: 'my-protfolio-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.website',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGtlOg8InrWTMs96Ch7snJ3SgcbuzfsZQ',
    appId: '1:246973295693:web:8b2323a487e7193ddc0004',
    messagingSenderId: '246973295693',
    projectId: 'my-protfolio-dashboard',
    authDomain: 'my-protfolio-dashboard.firebaseapp.com',
    storageBucket: 'my-protfolio-dashboard.firebasestorage.app',
    measurementId: 'G-1RTVDNGGDH',
  );
}
